name = "car-insurance"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "car-insurance-db"
database_id = "ee330c17-bb87-40c7-965f-074131854fe8"

# Pages Functions 目录
[pages]
directory = "functions"
